batch_size: 2048
budget_strategy: adaptive
data_path: ./data/amazon-book
dataset: ''
decay: 0.0001
delta: 1.0e-05
early_stop_patience: 10
emb_dim: 64
enable_dp: true
epochs: 60
epsilon:
- 5
- 10
- 20
eval_interval: 20
lr: 0.001
n_layers: 3
seed: 2024
sensitivity: 1.0
top_k: 20
